# Generated by Django 3.2.23 on 2024-03-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_alter_contact_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="subject",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
