# Generated by Django 3.2.23 on 2024-02-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20240225_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='blog/default.jpg', upload_to='blog/'),
        ),
    ]
