# Generated by Django 3.2.23 on 2024-03-04 14:52

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20240301_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='logo_image',
            field=django_resized.forms.ResizedImageField(crop=None, default='blog/c5.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[60, 60], upload_to='blog/'),
        ),
    ]
