# Generated by Django 5.0.3 on 2024-03-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='E:/Django course/mysite/media/blog/default.jpg', upload_to='blog/'),
        ),
    ]
