# Generated by Django 5.0.3 on 2024-03-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='statics/img/blog/feature-img1.jpg', upload_to='blog/'),
        ),
    ]
